# Generated by Django 2.1.7 on 2020-02-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='评分')),
                ('commentNumber', models.IntegerField(default=0, verbose_name='评论数')),
                ('positiveCommentNumber', models.IntegerField(default=0, verbose_name='好评数')),
                ('negativeCommentNumber', models.IntegerField(default=0, verbose_name='差评数')),
            ],
            options={
                'verbose_name': '评论统计',
                'verbose_name_plural': '评论统计',
                'db_table': 'comment_counts',
            },
        ),
    ]
