# Generated by Django 2.1.7 on 2020-05-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0002_auto_20200202_1400'),
        ('tourist_spots', '0002_remove_touristattraction_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('image', models.URLField(verbose_name='配图')),
                ('likeCounts', models.IntegerField(default=0, verbose_name='点赞数')),
                ('url', models.URLField(verbose_name='文章地址')),
                ('pubDate', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('recommendedRestaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='restaurant.Restaurant', verbose_name='推荐餐厅')),
                ('recommendedTourist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='tourist_spots.TouristAttraction', verbose_name='推荐景点')),
            ],
            options={
                'verbose_name': '文化卡片',
                'verbose_name_plural': '文化卡片',
                'db_table': 'tb_culture',
                'ordering': ['-pubDate'],
            },
        ),
        migrations.CreateModel(
            name='CultureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='类别名')),
            ],
            options={
                'verbose_name': '文化卡片类别',
                'verbose_name_plural': '文化卡片类别',
                'db_table': 'tb_culture_type',
            },
        ),
        migrations.AddField(
            model_name='culture',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='culture.CultureType', verbose_name='类别'),
        ),
    ]
