# Generated by Django 2.1.7 on 2020-05-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='recommendedRestaurant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='restaurant.Restaurant', verbose_name='推荐餐厅'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='recommendedTourist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tourist_spots.TouristAttraction', verbose_name='推荐景点'),
        ),
    ]
