# Generated by Django 2.1.7 on 2020-02-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='昵称')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('gender', models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('address', models.CharField(blank=True, max_length=120, null=True, verbose_name='地址')),
                ('birth', models.CharField(blank=True, max_length=12, null=True, verbose_name='生日')),
                ('introduce', models.CharField(blank=True, max_length=160, null=True, verbose_name='个人说明')),
                ('imgUrl', models.URLField(default='http://img.pconline.com.cn/images/upload/upc/tx/itbbs/1809/27/c23/111618645_1538043530897_mthumb.jpg', null=True, verbose_name='头像地址')),
                ('createTime', models.CharField(max_length=12, verbose_name='创建时间')),
                ('status', models.BooleanField(default=0, verbose_name='账号是否可用')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'ordering': ['phone'],
            },
        ),
    ]
