# Generated by Django 2.1.7 on 2020-02-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createTime',
            field=models.DateField(auto_now_add=True, verbose_name='账号创建时间'),
        ),
    ]
