# Generated by Django 2.1.7 on 2020-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200205_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fansNum',
            field=models.IntegerField(default=0, verbose_name='粉丝数'),
        ),
        migrations.AddField(
            model_name='user',
            name='focusNum',
            field=models.IntegerField(default=0, verbose_name='关注数'),
        ),
        migrations.AddField(
            model_name='user',
            name='trendNum',
            field=models.IntegerField(default=0, verbose_name='动态数'),
        ),
    ]
