# Generated by Django 2.1.7 on 2020-05-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200206_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fansNum',
        ),
        migrations.RemoveField(
            model_name='user',
            name='focusNum',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trendNum',
        ),
    ]
