# Generated by Django 2.1.7 on 2020-05-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200514_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imgUrl',
            field=models.URLField(default='http://img3.imgtn.bdimg.com/it/u=1915964370,308407353&fm=26&gp=0.jpg', null=True, verbose_name='头像地址'),
        ),
    ]
