# Generated by Django 2.1.7 on 2020-05-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imgUrl',
            field=models.URLField(default='http://39.96.63.142/images/tianxiadat .png', null=True, verbose_name='头像地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(default='暂无个人介绍', max_length=160, verbose_name='个人说明'),
        ),
    ]
