# Generated by Django 2.1.7 on 2020-05-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelnote',
            name='tag',
            field=models.ManyToManyField(to='travel_tag.Tag', verbose_name='标签'),
        ),
    ]
