# Generated by Django 2.1.7 on 2020-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('imgUrl', models.URLField(verbose_name='封面图片地址')),
                ('kind', models.BooleanField(choices=[(0, '引用文章'), (1, '跳转外部应用')], verbose_name='类型')),
                ('contentUrl', models.URLField(verbose_name='内容地址')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'bannner',
            },
        ),
    ]
