# Generated by Django 2.1.7 on 2020-05-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_auto_20200516_1008'),
        ('travel_tag', '0002_auto_20200513_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('likeCounts', models.IntegerField(default=0, verbose_name='点赞数')),
                ('pubDate', models.DateField(auto_now=True, verbose_name='发布时间')),
                ('tag', models.ManyToManyField(to='travel_tag.Tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
                'db_table': 'tb_trends',
                'ordering': ['-pubDate'],
            },
        ),
        migrations.CreateModel(
            name='TrendsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论')),
                ('date', models.DateField(auto_now_add=True, verbose_name='评论时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.TrendsComment', verbose_name='子评论')),
                ('trends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Trends', verbose_name='动态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '动态评论',
                'verbose_name_plural': '动态评论',
                'db_table': 'tb_trends_comment',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrendsCommentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.TrendsComment', verbose_name='动态评论')),
            ],
            options={
                'verbose_name': '动态评论配图',
                'verbose_name_plural': '动态评论配图',
                'db_table': 'tb_trends_comment_image',
            },
        ),
        migrations.CreateModel(
            name='TrendsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('trends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Trends', verbose_name='动态配图')),
            ],
            options={
                'verbose_name': '动态配图',
                'verbose_name_plural': '动态配图',
                'db_table': 'tb_trend_image',
                'ordering': ['trends'],
            },
        ),
    ]
