# Generated by Django 2.1.7 on 2020-05-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendscomment',
            name='comment',
        ),
    ]
