# Generated by Django 2.1.7 on 2020-05-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_remove_trendscomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendscomment',
            name='likeCounts',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
