# Generated by Django 2.1.7 on 2020-05-18 11:43

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='视频名')),
                ('file', models.FileField(upload_to=videos.models.user_directory_path, verbose_name='视频文件')),
                ('date', models.DateField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '视频管理',
                'verbose_name_plural': '视频管理',
                'db_table': 'tb_video',
                'ordering': ['-date'],
            },
        ),
    ]
