# Generated by Django 2.1.7 on 2020-05-16 08:38

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image.models.user_directory_path, verbose_name='配图')),
            ],
            options={
                'verbose_name': '图片管理',
                'verbose_name_plural': '图片管理',
                'db_table': 'tb_images',
            },
        ),
    ]
