# Generated by Django 2.1.7 on 2020-05-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_auto_20200516_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120, verbose_name='评论内容')),
                ('date', models.DateField(auto_now_add=True, verbose_name='评论时间')),
                ('likeCounts', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '求助评论',
                'verbose_name_plural': '求助评论',
                'db_table': 'tb_help_comment',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HelpCommnetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('helpComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seek_help.HelpComment', verbose_name='评论')),
            ],
            options={
                'verbose_name': '求助评论配图',
                'verbose_name_plural': '求助评论配图',
                'db_table': 'tb_help_comment_image',
            },
        ),
        migrations.CreateModel(
            name='HelpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='求助内容')),
                ('status', models.BooleanField(choices=[(0, '已解决'), (1, '未解决')], default=1, verbose_name='状态')),
                ('commentCount', models.IntegerField(default=0, verbose_name='评论数')),
                ('pubDate', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('tag', models.CharField(max_length=36, null=True, verbose_name='关键词')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '求助信息',
                'verbose_name_plural': '求助信息',
                'db_table': 'tb_seek_help',
                'ordering': ['-pubDate', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='HelpInfoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seek_help.HelpInfo', verbose_name='求助信息')),
            ],
            options={
                'verbose_name': '求助信息配图',
                'verbose_name_plural': '求助信息配图',
                'db_table': 'tb_seek_help_image',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='helpcomment',
            name='helpInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seek_help.HelpInfo', verbose_name='求助信息'),
        ),
        migrations.AddField(
            model_name='helpcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
