# Generated by Django 2.1.7 on 2020-02-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment_counts', '0001_initial'),
        ('open_date_time', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='餐厅名')),
                ('position', models.CharField(max_length=120, verbose_name='位置')),
                ('averageConsumption', models.IntegerField(verbose_name='平均消费')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('phone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('commentCount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comment_counts.CommentCounts', verbose_name='评论统计')),
                ('openDate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_date_time.OpenDate', verbose_name='营业时间')),
            ],
            options={
                'verbose_name': '餐厅',
                'verbose_name_plural': '餐厅',
                'db_table': 'restaurant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('public_time', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('manner', models.BooleanField(choices=[(0, '好评'), (1, '差评')], default=0, verbose_name='好评or差评')),
                ('isQuality', models.BooleanField(choices=[(0, '是'), (1, '不是')], default=1, verbose_name='是否是优质评论')),
                ('stars', models.DecimalField(blank=True, decimal_places=1, default=5.0, max_digits=2, verbose_name='评分')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant', verbose_name='餐厅')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '餐厅评论',
                'verbose_name_plural': '餐厅评论',
                'db_table': 'restaurant_comment',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCommentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('restaurantComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.RestaurantComment', verbose_name='餐厅评论')),
            ],
            options={
                'verbose_name': '餐厅评论配图',
                'verbose_name_plural': '餐厅评论配图',
                'db_table': 'restaurant_comment_image',
                'ordering': ['restaurantComment'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='菜名')),
                ('restaurant', models.ManyToManyField(to='restaurant.Restaurant', verbose_name='餐厅')),
            ],
            options={
                'verbose_name': '餐厅菜系',
                'verbose_name_plural': '餐厅菜系',
                'db_table': 'restaurant_food',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant', verbose_name='餐厅')),
            ],
            options={
                'verbose_name': '餐厅配图',
                'verbose_name_plural': '餐厅配图',
                'db_table': 'restaurant_images',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=36, verbose_name='餐厅标签')),
                ('restaurant', models.ManyToManyField(to='restaurant.Restaurant', verbose_name='餐厅')),
            ],
            options={
                'verbose_name': '餐厅标签',
                'verbose_name_plural': '餐厅标签',
                'db_table': 'restaurant_tag',
                'ordering': ['tag'],
            },
        ),
    ]
