# Generated by Django 2.1.7 on 2020-02-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttag',
            name='tag',
            field=models.CharField(max_length=36, verbose_name='标签'),
        ),
    ]
