# Generated by Django 2.1.7 on 2020-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '游记攻略动态标签',
                'verbose_name_plural': '游记攻略动态标签',
                'db_table': 'tb_travel_tag',
            },
        ),
    ]
