# Generated by Django 2.1.7 on 2020-05-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tb_tag',
        ),
    ]
