# Generated by Django 2.1.7 on 2020-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.TextField(verbose_name='开放日期')),
                ('open_time', models.TextField(verbose_name='开放时间')),
            ],
            options={
                'verbose_name': '开放日期',
                'verbose_name_plural': '开放时间',
                'db_table': 'open_date',
            },
        ),
    ]
