# Generated by Django 2.1.7 on 2020-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_date_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendate',
            name='open_date',
            field=models.TextField(blank=True, null=True, verbose_name='开放日期'),
        ),
        migrations.AlterField(
            model_name='opendate',
            name='open_time',
            field=models.TextField(blank=True, null=True, verbose_name='开放时间'),
        ),
    ]
