# Generated by Django 2.1.7 on 2020-05-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200206_1948'),
        ('travel_tag', '0002_auto_20200513_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('likeCounts', models.IntegerField(default=0, verbose_name='点赞数')),
                ('pubDate', models.DateField(auto_now=True, verbose_name='发布时间')),
                ('address', models.CharField(max_length=120, verbose_name='地点')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('tag', models.ManyToManyField(to='travel_tag.Tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '攻略',
                'verbose_name_plural': '攻略',
                'db_table': 'tb_strategy',
                'ordering': ['-pubDate'],
            },
        ),
        migrations.CreateModel(
            name='StrategyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.Strategy', verbose_name='攻略')),
            ],
            options={
                'verbose_name': '攻略配图',
                'verbose_name_plural': '攻略配图',
                'db_table': 'tb_strategy_image',
            },
        ),
    ]
