# Generated by Django 2.1.7 on 2020-01-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True, verbose_name='美食名')),
                ('description', models.TextField(verbose_name='美食简介')),
                ('story', models.TextField(verbose_name='美食故事')),
                ('feature', models.TextField(verbose_name='美食特点')),
                ('practice', models.TextField(verbose_name='美食做法')),
                ('value', models.TextField(verbose_name='营养价值')),
                ('tag', models.CharField(max_length=36, verbose_name='美食标签')),
                ('likeCounts', models.IntegerField(verbose_name='喜欢人数')),
            ],
            options={
                'verbose_name': '美食',
                'verbose_name_plural': '美食',
                'db_table': 'food',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('food', models.ForeignKey(on_delete='所属美食', to='food.Food')),
            ],
            options={
                'verbose_name': '美食配图',
                'verbose_name_plural': '美食配图',
                'db_table': 'food_imgs',
                'ordering': ['id'],
            },
        ),
    ]
