# Generated by Django 2.1.7 on 2020-02-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_recommendedrestauran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='recommendedRestauran',
            new_name='recommendedRestaurant',
        ),
    ]
