# Generated by Django 2.1.7 on 2020-02-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200202_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='recommendedRestaurant',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='restaurant.Restaurant', verbose_name='推荐餐厅'),
        ),
    ]
