# Generated by Django 2.1.7 on 2020-02-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200207_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='recommendedRestaurant',
            field=models.ManyToManyField(to='restaurant.Restaurant', verbose_name='推荐餐厅'),
        ),
    ]
