# Generated by Django 2.1.7 on 2020-05-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(upload_to='2020-05-16 16:05:15.536576/', verbose_name='配图'),
        ),
    ]
