# Generated by Django 2.1.7 on 2020-05-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200516_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(upload_to="<attribute 'year' of 'datetime.date' objects><attribute 'month' of 'datetime.date' objects><attribute 'day' of 'datetime.date' objects>/", verbose_name='配图'),
        ),
    ]
