# Generated by Django 2.1.7 on 2020-05-16 08:21

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200516_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(upload_to=diary.models.user_directory_path, verbose_name='配图'),
        ),
    ]
